services:
  monolito:
    build:
      context: ./Monolito
      dockerfile: Dockerfile
    container_name: mws-monolito
    ports:
      - "8080:80"
    volumes:
      - ./Monolito/mws:/var/www/html
    networks:
      - mws-network

  db:
    image: mysql:8.0
    container_name: mws-db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    environment:
      MYSQL_DATABASE: mws_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    networks:
      - mws-network
    volumes:
      - mws_db_data:/var/lib/mysql

  cliente-lv-api:
    build:
      context: ./Microservicos-lv/php84/Cliente-lv
    container_name: cliente-lv-api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    ports:
      - "8001:80"
    volumes:
      - ./Microservicos-lv/php84/Cliente-lv:/var/www/html
    networks:
      mws-network:
        aliases:
          - cliente-lv
    depends_on:
      - db

  veiculo-lv-api:
    build:
      context: ./Microservicos-lv/php84/Veiculo-lv
    container_name: veiculo-lv-api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    ports:
      - "8002:80"
    volumes:
      - ./Microservicos-lv/php84/Veiculo-lv:/var/www/html
    networks:
      mws-network:
        aliases:
          - veiculo-lv
    depends_on:
      - db

  estoque-lv-api:
    build:
      context: ./Microservicos-lv/php84/Estoque-lv
    container_name: estoque-lv-api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    ports:
      - "8003:80"
    volumes:
      - ./Microservicos-lv/php84/Estoque-lv:/var/www/html
    networks:
      mws-network:
        aliases:
          - estoque-lv
    depends_on:
      - db

  funcionario-lv-api:
    build:
      context: ./Microservicos-lv/php84/Funcionario-lv
    container_name: funcionario-lv-api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    ports:
      - "8004:80"
    volumes:
      - ./Microservicos-lv/php84/Funcionario-lv:/var/www/html
    networks:
      mws-network:
        aliases:
            - funcionario-lv
    depends_on:
      - db

  os-lv-api:
    build:
      context: ./Microservicos-lv/php84/Os-lv
    container_name: os-lv-api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    ports:
      - "8005:80"
    volumes:
      - ./Microservicos-lv/php84/Os-lv:/var/www/html
    networks:
      mws-network:
        aliases:
          - os-lv
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mws-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mws-network

networks:
  mws-network:
    driver: bridge

volumes:
  mws_db_data: