apiVersion: v1
kind: Service
metadata:
  name: funcionario-api
spec:
  selector:
    app: funcionario-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: funcionario-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funcionario-api
  template:
    metadata:
      labels:
        app: funcionario-api
    spec:
      containers:
        - name: funcionario-api
          image: pirolo/funcionario-api:v2
          ports:
            - containerPort: 80
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mws-db
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: mws_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root