apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-lv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente-lv
  template:
    metadata:
      labels:
        app: cliente-lv
    spec:
      containers:
        - name: cliente-lv
          image: pirolo/cliente-api:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mws-config

            - secretRef:
                name: mws-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cliente-lv
spec:
  selector:
    app: cliente-lv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80