apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolito-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolito
  template:
    metadata:
      labels:
        app: monolito
    spec:
      containers:
        - name: monolito
          image: 955465104750.dkr.ecr.us-east-1.amazonaws.com/monolito
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mws-config

            - secretRef:
                name: mws-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: monolito-service
spec:
  type: LoadBalancer
  selector:
    app: monolito
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80