name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-microservices:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - Cliente-lv
          - Veiculo-lv
          - Estoque-lv
          - Funcionario-lv
          - Os-lv

    defaults:
      run:
        working-directory: Microservicos-lv/php84/${{ matrix.service }}

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_mysql

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Criar .env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Executar testes
        run: php artisan test